### ISSUE TITLE
What browsers do we support?

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockRPG#28] opened 2015-09-28 15:43 UTC
Also, versions: just latest, latest - 1?

**Comment by RaceProUK** [comment] 2015-09-28 15:46
IE, Firefox, Chrome, Safari, Opera and the Big Five Browsers; we should at least try to support those. Versions is a bit trickier; what constitutes `latest` and `latest-1`?

**Comment by RaceProUK** [comment] 2015-09-28 15:56
There's also the matter of IE being a special snowflake, and not allowing v11 on XP (max v9) or Vista (max v10). And then there's Edge, which replaces IE on Win10.

**Comment by AccaliaDeElementia** [comment] 2015-09-28 18:11
Chrome, Firefox, Safari, and Opera should be tested for latest in current major version (i.e. `43.x.x`) and latest in previous major version (i.e. `42.x.x`)

IE..... do i have to support it?

11 and edge for certain. v9 is right out. i'm sorry but if you are still on XP then you don't need your sanity nearly as much as I do. I would say that IE10 would be supported but some degree of performance and feature degradation would be allowed.

**Comment by AccaliaDeElementia** [comment] 2015-09-28 18:11
also browsers should be checked on multiple OSes. because there are render bugs that only affect one browser on one OS.

**Comment by yamikuronue** [comment] 2015-09-28 18:15
"i'm sorry but if you are still on XP"

You are thinking of IE8. IE9 is available starting in Windows 7 (and is, in fact, what I've got availible at work)

**Comment by Onyx47** [comment] 2015-09-28 18:16
From personal experience, any testing in Opera should be there just to make extra sure. Except when dealing with WebRTC I always had full parity between Chrome and Opera.

Chromium, on the other hand, sometimes has issues due to being a bit behind on WebKit versions.

**Comment by AccaliaDeElementia** [comment] 2015-09-28 18:18
@yamikuronue, fair enough. I'm still not spending my development time supporting IE9.  IE10 is supported in Windows 7 and companies are very rapidly moving away from employees being locked into IE8 now that XP has been aggressively EOL'd

**Comment by Cloak15** [comment] 2015-09-28 21:01
Here's an interesting, and probably stupid question. Does XP even support
IE or IE10?


On Mon, Sep 28, 2015 at 2:18 PM, Accalia Elementia <notifications@github.com

**Comment by RaceProUK** [comment] 2015-09-28 21:03
Nothing newer than IE8 will run on XP. And nothing newer than IE9 will run on Vista.

https://en.wikipedia.org/wiki/Internet_Explorer_versions#Windows

**Comment by yamikuronue** [comment] 2015-09-28 21:04
That's what we were talking about: on XP, the last version of IE that's
supported is IE8. Windows 7 gets IE 9 and IE 10, and I think 8 got IE 11,
with 10 having anywhere from 9 to 11 depending on the upgrade path (I
think?) and also Edge, which is the new supported version

**Comment by RaceProUK** [comment] 2015-09-28 21:05
Well, technically 8 is stuck with IE10; you need to update it to 8.1 to get IE11.

**Comment by AccaliaDeElementia** [comment] 2015-09-28 21:40
Okay so, if i'm reading this all correctly we support the following setup:

Class A Support: Fully tested, any defect will be fixed:
* Current Major version and Previous major versions of
  * Chrome
  * Opera
  * Safari
  * Firefox
* IE11
* Windows Spartan/Edge/Whatevertheycallit

Class B support: 
Partial Testing, Experience degredation allowed so long as basic functionality works:
* IE10
* IE9

Class C support:
Not Tested, Pull requests to fix bugs accepted but will not expend Team Effort fixing bugs:
* Older versions of IE
* Versions of Class A browsers more than 2 major versions out of date (unless bug is reproduceable on a Class A browser patch level)

Class D support:
Personae non gratae
* IE7
* Emacs ( :stuck_out_tongue_winking_eye: )

Correct?

**Comment by Onyx47** [comment] 2015-09-28 21:49
> Versions of Class A browsers more than 2 major versions out of date (unless bug is reproduceable on a Class A browser patch level)

Is this far enough back for Chrome/Opera/FF? Those churn out versions faster than I can run updates on my system...

> Emacs ( :stuck_out_tongue_winking_eye: )

As long as `links` works... :P

**Comment by AccaliaDeElementia** [comment] 2015-09-28 21:52
> Is this far enough back for Chrome/Opera/FF? Those churn out versions faster than I can run updates on my system...

You have an alternate suggestion? I'm open to ideas here.

> As long as links works... :P

hmm..... well if you're good at reading JSON..... :stuck_out_tongue_closed_eyes:

**Comment by RaceProUK** [comment] 2015-09-28 22:00
>Is this far enough back for Chrome/Opera/FF? Those churn out versions faster than I can run updates on my system...

Users of those browsers I think tend to stay pretty up to date; Chrome is especially good at keeping itself up to date without the user even knowing it's happening, and Firefox has improved quite a bit in that respect too.

**Comment by Onyx47** [comment] 2015-09-28 22:08
Fair point on things being up to date... I retract my complaint.

**Comment by AccaliaDeElementia** [comment] 2015-09-29 11:21
Alright then, Unless there are further objections i believe @yamikuronue has her answer for our browser support policy:

https://github.com/SockDrawer/SockRPG/issues/28#issuecomment-143881969

**Closed by AccaliaDeElementia** 2015-09-29 11:21 UTC
Labels: question, Requirements clarification
